package;

@:enum
abstract ConstResource(String) {
    var RESOURCE_ENERGY = "energy";
    var RESOURCE_POWER  = "power";

    var RESOURCE_HYDROGEN   = "H";
    var RESOURCE_OXYGEN     = "O";
    var RESOURCE_UTRIUM     = "U";
    var RESOURCE_LEMERGIUM  = "L";
    var RESOURCE_KEANIUM    = "K";
    var RESOURCE_ZYNTHIUM   = "Z";
    var RESOURCE_CATALYST   = "X";
    var RESOURCE_GHODIUM    = "G";

    var RESOURCE_HYDROXIDE          = "OH";
    var RESOURCE_ZYNTHIUM_KEANITE   = "ZK";
    var RESOURCE_UTRIUM_LEMERGITE   = "UL";

    var RESOURCE_UTRIUM_HYDRIDE     = "UH";
    var RESOURCE_UTRIUM_OXIDE       = "UO";
    var RESOURCE_KEANIUM_HYDRIDE    = "KH";
    var RESOURCE_KEANIUM_OXIDE      = "KO";
    var RESOURCE_LEMERGIUM_HYDRIDE  = "LH";
    var RESOURCE_LEMERGIUM_OXIDE    = "LO";
    var RESOURCE_ZYNTHIUM_HYDRIDE   = "ZH";
    var RESOURCE_ZYNTHIUM_OXIDE     = "ZO";
    var RESOURCE_GHODIUM_HYDRIDE    = "GH";
    var RESOURCE_GHODIUM_OXIDE      = "GO";

    var RESOURCE_UTRIUM_ACID        = "UH2O";
    var RESOURCE_UTRIUM_ALKALIDE    = "UHO2";
    var RESOURCE_KEANIUM_ACID       = "KH2O";
    var RESOURCE_KEANIUM_ALKALIDE   = "KHO2";
    var RESOURCE_LEMERGIUM_ACID     = "LH2O";
    var RESOURCE_LEMERGIUM_ALKALIDE = "LHO2";
    var RESOURCE_ZYNTHIUM_ACID      = "ZH2O";
    var RESOURCE_ZYNTHIUM_ALKALIDE  = "ZHO2";
    var RESOURCE_GHODIUM_ACID       = "GH2O";
    var RESOURCE_GHODIUM_ALKALIDE   = "GHO2";

    var RESOURCE_CATALYZED_UTRIUM_ACID          = "XUH2O";
    var RESOURCE_CATALYZED_UTRIUM_ALKALIDE      = "XUHO2";
    var RESOURCE_CATALYZED_KEANIUM_ACID         = "XKH2O";
    var RESOURCE_CATALYZED_KEANIUM_ALKALIDE     = "XKHO2";
    var RESOURCE_CATALYZED_LEMERGIUM_ACID       = "XLH2O";
    var RESOURCE_CATALYZED_LEMERGIUM_ALKALIDE   = "XLHO2";
    var RESOURCE_CATALYZED_ZYNTHIUM_ACID        = "XZH2O";
    var RESOURCE_CATALYZED_ZYNTHIUM_ALKALIDE    = "XZHO2";
    var RESOURCE_CATALYZED_GHODIUM_ACID         = "XGH2O";
    var RESOURCE_CATALYZED_GHODIUM_ALKALIDE     = "XGHO2";
}
